# Generated by Django 4.0.6 on 2022-08-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.CharField(default='$', max_length=40),
            preserve_default=False,
        ),
    ]
