# Generated by Django 4.2.3 on 2023-10-05 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_students_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
