# Generated by Django 4.2.3 on 2023-09-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_remove_students_id_students_from_students_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='To',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
